CONFIG_DIRECTORY = "#{Dir.home}/.config"

MYSECRET_DIRECTORY = "#{CONFIG_DIRECTORY}/MySecret"

NOTES_DIRECTORY = "#{MYSECRET_DIRECTORY}/notes"

EDITOR_PATH = "#{MYSECRET_DIRECTORY}/editor.config"

IV_ALGORITHM = "MySecret"
